name: Arabic PDF fix

on:
  push:
    paths: ["**.pdf"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-ara ghostscript
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fix PDFs
        run: |
          for f in $(git ls-files '*.pdf' | grep -v -- '-readable\.pdf$'); do
            python fix_arabic_pdf.py "$f"
          done

      - name: Commit results
        run: |
          git config user.name  "pdf-bot"
          git config user.email "pdf-bot@users.noreply.github.com"
          git add *-readable.pdf
          git commit -m "Add readable Arabic PDFs" || echo "No changes"
          git push
